// GENERATED by scripts/sync-tools.mjs from the hosted server's tools/list — do not edit by hand.
// Names, descriptions, parameters and annotations are the hosted server's (mcp.competlab.com),
// word for word. Where each tool goes on the API is src/routes.ts.

export const SERVER_DESCRIPTION =
  "Competitive intelligence for B2B SaaS — monitor competitors across tech stack, content, positioning, pricing, AI visibility (how ChatGPT, Claude, Gemini, Perplexity and Google AI Overviews name and recommend your brand against competitors), and AI sources (the pages Perplexity and Google AI Overviews read when they answer your buyers' questions, and whether your brand is on them)";

export const SERVER_INSTRUCTIONS =
  "CompetLab is a competitive intelligence platform for B2B SaaS companies.\n" +
  "It monitors 6 dimensions across your competitors: Tech & Trust Profile, Content Intelligence,\n" +
  "Positioning, Pricing Intelligence, AI Visibility, and AI Sources.\n" +
  "\n" +
  "READING THE DATA, on every tool: null means WE DID NOT MEASURE IT, never zero, empty, false, or \"no\". " +
  "A measured 0, false or empty list is reported as itself. " +
  "A reason, where one exists, is in a sibling \"…Available\" object; a null with no marker is still not a zero. " +
  "Never write \"they have no X\" from a null: say the check did not complete, and what is still known. " +
  "An empty list means we looked and found none; a null list means we did not look.\n" +
  "\n" +
  "AI Visibility answers who the AI models (ChatGPT, Claude, Gemini, Perplexity, and Google AI Overviews) recommend for industry queries and where the customer stands: Core, Too early to tell, or Rarely recommended. " +
  "Brands are ordered by how often they are named; Google AI Overviews ranks nothing and counts for presence only.\n" +
  "\n" +
  "AI Sources is its companion: for Perplexity and Google AI Overviews it asks a project's 8 buying questions and reads the pages each engine retrieved. " +
  "RETRIEVED, never cited; PER ENGINE, never pooled; COUNTS, never rates: n of N answers, never a percentage. " +
  "A page we could not read is listed, never counted as one the brand is absent from.\n" +
  "\n" +
  "Strategic Tickets is the project's board, the one the team sees in the app; list_tickets says how to read it.\n" +
  "\n" +
  "Tools with a view parameter default to compact here: long lists paged, the customer's row kept; view=full returns everything. " +
  "readingGuide, first in each response, carries each field's rule. " +
  "A check detail asked for answers omits its summary unless includeSummary=true.\n" +
  "\n" +
  "Start: list_projects, get_project (freshness), a dimension dashboard, list_alerts. " +
  "The free tools (check_sitemap, check_ai_crawlers, fetch_url, and the scans) take a domain and need no project. " +
  "Paged tools take page and limit: read pagination.hasMore.";
